DROP TABLE IF EXISTS organisateur CASCADE; 
DROP TABLE IF EXISTS evenement CASCADE; 
DROP TABLE IF EXISTS tournois CASCADE; 
DROP TABLE IF EXISTS terrain CASCADE; 
DROP TABLE IF EXISTS dispose CASCADE;
DROP TABLE IF EXISTS equipe CASCADE;
DROP TABLE IF EXISTS joueur CASCADE; 