--TEST DES CONTRAINTES
/*
INSERT INTO terrain VALUES (100, '100m');

INSERT INTO evenement VALUES (100, 'oui', '2020-10-10', 15, 0001);
INSERT INTO evenement VALUES (101, 'oui', '2020-10-10', 0, 0001);

INSERT INTO tournois VALUES (100, 'oui', NULL, 0, 01);
INSERT INTO tournois VALUES (102, 'oui', NULL, 16, 01);

INSERT INTO joueur VALUES (100, NULL, NULL, 10, 'Galatix');
INSERT INTO joueur VALUES (101, NULL, NULL, 0, 'Galatix');
*/

--TEST DES TRIGGERS
/*
--secure_Tailleclassement
--nombre de caractères du classement supérieur à 495 :
INSERT INTO tournois VALUES(103, 'tournois3','EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',5, 01);

--secure_NomEquipe
--nom d'équipe contenant ' ', '-' ou '_' :
INSERT INTO equipe VALUES(100, ' t-_-_e -s -t_ ', NULL, 03);

*/ 